import { GPIO_1, GPIO_2, GPIO_3, GPIO_4, GPIO_5, GPIO_6, GPIO_7, GPIO_8, GPIO_9, GPIO_10, GPIO_11, GPIO_12, GPIO_13, GPIO_14, GPIO_15, GPIO_16, GPIO_17, GPIO_18, GPIO_19, GPIO_20, GPIO_21, GPIO_22, GPIO_23, GPIO_24, GPIO_25, GPIO_26 } from "./stores"

export const gpioPins = [
    { label: "GPIO 1", data: GPIO_1 },
    { label: "GPIO 2", data: GPIO_2 },
    { label: "GPIO 3", data: GPIO_3 },
    { label: "GPIO 4", data: GPIO_4 },
    { label: "GPIO 5", data: GPIO_5 },
    { label: "GPIO 6", data: GPIO_6 },
    { label: "GPIO 7", data: GPIO_7 },
    { label: "GPIO 8", data: GPIO_8 },
    { label: "GPIO 9", data: GPIO_9 },
    { label: "GPIO 10", data: GPIO_10 },
    { label: "GPIO 11", data: GPIO_11 },
    { label: "GPIO 12", data: GPIO_12 },
    { label: "GPIO 13", data: GPIO_13 },
    { label: "GPIO 14", data: GPIO_14 },
    { label: "GPIO 15", data: GPIO_15 },
    { label: "GPIO 16", data: GPIO_16 },
    { label: "GPIO 17", data: GPIO_17 },
    { label: "GPIO 18", data: GPIO_18 },
    { label: "GPIO 19", data: GPIO_19 },
    { label: "GPIO 20", data: GPIO_20 },
    { label: "GPIO 21", data: GPIO_21 },
    { label: "GPIO 22", data: GPIO_22 },
    { label: "GPIO 23", data: GPIO_23 },
    { label: "GPIO 24", data: GPIO_24 },
    { label: "GPIO 25", data: GPIO_25 },
    { label: "GPIO 26", data: GPIO_26 },
]